name: Workflow
on:
    push:
        branches:
            - feat-devsecops

Jobs:
    Build:
        Runs-on: ubuntu-latest
        Steps:

        - name: Hola Mundo
        Run: |
            echo "hola Mundo"
