name: Workflow
on:
    push:
        branches:
            - "feature-german2"

jobs:
    build:
        Runs-on: ubuntu-latest
        Steps:

        - name: Hola Mundo
        run: |
            echo "hola Mundo"